//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaLoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresseTable
    {
        public AdresseTable()
        {
            this.LocataireTables = new HashSet<LocataireTable>();
            this.NoteTables = new HashSet<NoteTable>();
            this.ProprietaireTables = new HashSet<ProprietaireTable>();
        }
    
        public int AdresseId { get; set; }
        public string AptNo { get; set; }
        public Nullable<int> RueNo { get; set; }
        public string Rue { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public string Pays { get; set; }
        public string GeoCodeResponse { get; set; }
        public Nullable<int> Longitude { get; set; }
        public Nullable<int> Lattitude { get; set; }
    
        public virtual ICollection<LocataireTable> LocataireTables { get; set; }
        public virtual ICollection<NoteTable> NoteTables { get; set; }
        public virtual ICollection<ProprietaireTable> ProprietaireTables { get; set; }
    }
}
