//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NoteTaLoc.Models
{
    public partial class CriteriaTable
    {
        public int CriteriaId { get; set; }
        public int NoteId { get; set; }
        public int Criteria { get; set; }
        public int Category { get; set; }
        public int Note { get; set; }
    
        public virtual NoteTable NoteTable { get; set; }
    }
    
}
