//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaLoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocataireTable
    {
        public int LocataireId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdresseId { get; set; }
        public Nullable<bool> PreuveDeDomicile { get; set; }
        public string PreuveType { get; set; }
    
        public virtual AdresseTable AdresseTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
