//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaLoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocataireTable
    {
        public int LocataireId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdresseId { get; set; }
        public Nullable<bool> PreuveDeDomicile { get; set; }
        public string PreuveType { get; set; }
    
        public virtual AdresseTable AdresseTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
