//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaLoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notetalocEntities : DbContext
    {
        public notetalocEntities()
            : base("name=notetalocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdresseTable> AdresseTables { get; set; }
        public DbSet<LocataireTable> LocataireTables { get; set; }
        public DbSet<NoteTable> NoteTables { get; set; }
        public DbSet<ProprietaireTable> ProprietaireTables { get; set; }
        public DbSet<SampleDroppableTable> SampleDroppableTables { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
    }
}
