//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaLoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notetalocEntities : DbContext
    {
        public notetalocEntities()
            : base("name=notetalocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdresseTable> AdresseTables { get; set; }
        public DbSet<LocataireTable> LocataireTables { get; set; }
        public DbSet<NoteTable> NoteTables { get; set; }
        public DbSet<ProprietaireTable> ProprietaireTables { get; set; }
        public DbSet<SampleDroppableTable> SampleDroppableTables { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
    }
}
