//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NoteTaLoc.Models
{
    public partial class ProprietaireTable
    {
        public int ProprietaireId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdresseId { get; set; }
        public Nullable<bool> PreuveDeProp { get; set; }
        public string PreuveType { get; set; }
    
        public virtual AdresseTable AdresseTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
    
}
