//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteTaLoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDroppableTable
    {
        public string Adresse { get; set; }
        public Nullable<int> Note { get; set; }
    }
}
