//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NoteTaLoc.Models
{
    public partial class UserTable
    {
        public UserTable()
        {
            this.LocataireTables = new HashSet<LocataireTable>();
            this.NoteTables = new HashSet<NoteTable>();
            this.ProprietaireTables = new HashSet<ProprietaireTable>();
        }
    
        public int UserId { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Pseudo { get; set; }
        public string MotDePasse { get; set; }
        public string Courriel { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public Nullable<System.DateTime> DateMod { get; set; }
        public Nullable<int> Statut { get; set; }
        public string Commentaire { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<bool> InscriptionConfirm { get; set; }
        public Nullable<bool> SiteCondAccept { get; set; }
        public Nullable<bool> AllowPubContact { get; set; }
        public string ValidationToken { get; set; }
    
        public virtual ICollection<LocataireTable> LocataireTables { get; set; }
        public virtual ICollection<NoteTable> NoteTables { get; set; }
        public virtual ICollection<ProprietaireTable> ProprietaireTables { get; set; }
    }
    
}
